version: '3.4'

services:
  backend:
    image: backend
    build:
      context: Backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
